name: Tests and checks
on:
  pull_request:

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run lint
        run: yarn lint
      - name: Run check types
        run: yarn check-types

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Check Foundry installation
        run: |
          anvil --version
          cast --version
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test:run
